export const images = {
    about: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834240/about_nk3ru4.png",
    backIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834233/back-icon_ulhqrs.png",
    collegeVideo: "https://res.cloudinary.com/ducnuoc3q/video/upload/f_auto,q_auto,w_auto,c_scale/v1766834273/college-video_akyrmp.mp4",
    darkArrow: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834235/dark-arrow_xpoe28.png",
    gallery1: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834250/gallery-1_iccl37.png",
    gallery2: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834243/gallery-2_gbm2ix.png",
    gallery3: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834253/gallery-3_smi4ty.png",
    gallery4: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834266/gallery-4_i349p5.png",
    hero: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834304/hero_snrkym.png",
    locationIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834303/location-icon_r1a9vu.png",
    logo: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834330/logo_cq9crn.png",
    mailIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834331/mail-icon_xjlrjd.png",
    menuIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834332/menu-icon_wdjtm4.png",
    msgIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834346/msg-icon_xmxbsn.png",
    nextIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834369/next-icon_fclxee.png",
    phoneIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834370/phone-icon_uzyppe.png",
    playIcon: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834370/play-icon_u7oo2j.png",
    program1: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834371/program-1_fjft2u.png",
    program2: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834371/program-2_yvel2x.png",
    program3: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834372/program-3_ldnqcn.png",
    programIcon1: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834375/program-icon-1_sqbhxl.png",
    programIcon2: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834375/program-icon-2_qfh0bm.png",
    programIcon3: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834375/program-icon-3_rbrbtu.png",
    user1: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834375/user-1_ykecj9.png",
    user2: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834376/user-2_g4sbxz.png",
    user3: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834376/user-3_dkbid0.png",
    user4: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834376/user-4_rpuy7s.png",
    whiteArrow: "https://res.cloudinary.com/ducnuoc3q/image/upload/f_auto,q_auto,w_auto,c_scale/v1766834376/white-arrow_in87kn.png",
};
// f_auto,q_auto,w_auto,c_scale yeh add karn ha images ke link ma takay optimized images load hon cloudinary sy